name: Unit Tests

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*.*.*'
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use npm 8
        run: |
          npm install --location=global npm@8
      - name: Install dependencies
        run: |
          npm install

      - name: Transpile for Node.js ${{ matrix.node-version }}
        run: |
          ./node_modules/.bin/lerna exec --bail --concurrency 2 -- ../../node_modules/.bin/swc --config-file ../../swc.cjs.config.json --source-maps false index.js --out-file index.cjs
          ./node_modules/.bin/lerna exec --bail --concurrency 2 -- sed -i.bak 's/exports,\ \"default\"/module,\ \"exports\"/g' index.cjs # Fix CommonJS default import
          ./node_modules/.bin/lerna exec --bail --concurrency 2 -- ../../node_modules/.bin/swc --config-file ../../swc.esm.config.json --source-maps false index.js --out-file index.js

      - name: Unit tests
        run: |
          npm run test:packages:unit

      - name: Test cjs can be required
        run: |
          node -e 'const middy = require("./packages/core/index.cjs"); middy()'
          node -e 'const {transpileSchema} = require("./packages/validator/transpile.cjs"); transpileSchema({});'
